version: '3.7'
services:
  catraca:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SERVER_PORT: 8082
      APP_LOG_ROOT: /var/log/services
    ports:
    - "8082:8082"
    restart: unless-stopped
